export const data = [
    {
    "id": 1,
    "property_type": "Single Room",
    "amount": 2,
    "location": "Brazil",
    "property_title": "House for rent",
    "status": 2
}, {
    "id": 2,
    "property_type": "Single Room",
    "amount": 3,
    "location": "Portugal",
    "property_title": "Single room for rent",
    "status": 1
}, {
    "id": 3,
    "property_type": "Apartment",
    "amount": 3,
    "location": "Russia",
    "property_title": "Single room for rent",
    "status": 3
}, {
    "id": 4,
    "property_type": "Apartment",
    "amount": 3,
    "location": "Greece",
    "property_title": "Single room for rent",
    "status": 2
}, {
    "id": 5,
    "property_type": "Apartment",
    "amount": 2,
    "location": "Philippines",
    "property_title": "Single room for rent",
    "status": 1
}, {
    "id": 6,
    "property_type": "Single Room",
    "amount": 1,
    "location": "France",
    "property_title": "House for rent",
    "status": 3
}, {
    "id": 7,
    "property_type": "Single Room",
    "amount": 2,
    "location": "Philippines",
    "property_title": "New apartment for rent",
    "status": 2
}, {
    "id": 8,
    "property_type": "Apartment",
    "amount": 2,
    "location": "Indonesia",
    "property_title": "New apartment for rent",
    "status": 3
}, {
    "id": 9,
    "property_type": "Apartment",
    "amount": 2,
    "location": "China",
    "property_title": "Single room for rent",
    "status": 1
}, {
    "id": 10,
    "property_type": "Single Room",
    "amount": 2,
    "location": "Netherlands",
    "property_title": "New apartment for rent",
    "status": 3
    }
]


export const tenantsData = [{
    "id": 1,
    "first_name": "Jason",
    "last_name": "Casarino",
    "name": "Jason Casarino",
    "phone": "627-603-2912",
    "property_type": "Single Room",
    "location": "Čelinac",
    "number_duration": 8,
    "period": "month",
    "start_date": "4/3/2022",
    "end_date": "17/7/2022",
    "duration": "8 / month",
    "status": "Upcoming"
}, {
    "id": 2,
    "first_name": "Cassius",
    "last_name": "O'Donnell",
    "name": "Cassius O'Donnell",
    "phone": "144-598-7607",
    "property_type": "Apartment",
    "location": "Leńcze",
    "number_duration": 10,
    "period": "week",
    "start_date": "9/4/2022",
    "end_date": "11/8/2021",
    "duration": "10 / week",
    "status": "Upcoming"
}, {
    "id": 3,
    "first_name": "Daisey",
    "last_name": "Piens",
    "name": "Daisey Piens",
    "phone": "682-729-8159",
    "property_type": "Single Room",
    "location": "Sigaboy",
    "number_duration": 1,
    "period": "year",
    "start_date": "27/5/2022",
    "end_date": "24/9/2021",
    "duration": "1 / year",
    "status": "Upcoming"
}, {
    "id": 4,
    "first_name": "Allayne",
    "last_name": "Telford",
    "name": "Allayne Telford",
    "phone": "486-353-8610",
    "property_type": "Single Room",
    "location": "København",
    "number_duration": 7,
    "period": "month",
    "start_date": "25/8/2021",
    "end_date": "1/1/2022",
    "duration": "7 / month",
    "status": "Upcoming"
}, {
    "id": 5,
    "first_name": "Carroll",
    "last_name": "Maypes",
    "name": "Carroll Maypes",
    "phone": "513-760-4096",
    "property_type": "Single Room",
    "location": "Saint-Félicien",
    "number_duration": 6,
    "period": "week",
    "start_date": "22/5/2022",
    "end_date": "18/9/2021",
    "duration": "6 / week",
    "status": "Current"
}, {
    "id": 6,
    "first_name": "Ilene",
    "last_name": "Cheers",
    "name": "Ilene Cheers",
    "phone": "717-478-4300",
    "property_type": "Apartment",
    "location": "Lazaro Cardenas",
    "number_duration": 11,
    "period": "year",
    "start_date": "13/8/2021",
    "end_date": "19/7/2022",
    "duration": "11 / year",
    "status": "Current"
}, {
    "id": 7,
    "first_name": "Prudence",
    "last_name": "Wallwork",
    "name": "Prudence Wallwork",
    "phone": "248-373-2032",
    "property_type": "Apartment",
    "location": "Ishim",
    "number_duration": 1,
    "period": "year",
    "start_date": "31/12/2021",
    "end_date": "4/4/2022",
    "duration": "1 / year",
    "status": "Current"
}, {
    "id": 8,
    "first_name": "Josy",
    "last_name": "Grant",
    "name": "Josy Grant",
    "phone": "782-413-4487",
    "property_type": "Apartment",
    "location": "Huicheng",
    "number_duration": 3,
    "period": "year",
    "start_date": "29/12/2021",
    "end_date": "24/12/2021",
    "duration": "3 / year",
    "status": "Current"
}, {
    "id": 9,
    "first_name": "Rochell",
    "last_name": "Eam",
    "name": "Rochell Eam",
    "phone": "867-314-6926",
    "property_type": "Single Room",
    "location": "Sremčica",
    "number_duration": 4,
    "period": "year",
    "start_date": "11/2/2022",
    "end_date": "22/6/2022",
    "duration": "4 / year",
    "status": "Upcoming"
}, {
    "id": 10,
    "first_name": "Dix",
    "last_name": "Sawkins",
    "name": "Dix Sawkins",
    "phone": "120-198-1416",
    "property_type": "Single Room",
    "location": "Preobrazhenka",
    "number_duration": 1,
    "period": "month",
    "start_date": "9/9/2021",
    "end_date": "3/6/2022",
    "duration": "1 / month",
    "status": "Upcoming"
}, {
    "id": 11,
    "first_name": "Clem",
    "last_name": "Coggles",
    "name": "Clem Coggles",
    "phone": "312-547-5277",
    "property_type": "Single Room",
    "location": "Ulety",
    "number_duration": 5,
    "period": "year",
    "start_date": "8/3/2022",
    "end_date": "29/8/2021",
    "duration": "5 / year",
    "status": "Upcoming"
}, {
    "id": 12,
    "first_name": "Cacilia",
    "last_name": "Dymidowski",
    "name": "Cacilia Dymidowski",
    "phone": "859-569-2906",
    "property_type": "Single Room",
    "location": "Hernández",
    "number_duration": 1,
    "period": "month",
    "start_date": "20/8/2021",
    "end_date": "28/9/2021",
    "duration": "1 / month",
    "status": "Past"
}, {
    "id": 13,
    "first_name": "Mattie",
    "last_name": "Viall",
    "name": "Mattie Viall",
    "phone": "427-873-5922",
    "property_type": "Apartment",
    "location": "Vila Nova Sintra",
    "number_duration": 8,
    "period": "year",
    "start_date": "16/10/2021",
    "end_date": "7/6/2022",
    "duration": "8 / year",
    "status": "Current"
}, {
    "id": 14,
    "first_name": "Hilary",
    "last_name": "Cockerton",
    "name": "Hilary Cockerton",
    "phone": "626-827-5710",
    "property_type": "Apartment",
    "location": "Luoxi",
    "number_duration": 10,
    "period": "week",
    "start_date": "12/8/2021",
    "end_date": "12/5/2022",
    "duration": "10 / week",
    "status": "Upcoming"
}, {
    "id": 15,
    "first_name": "Greg",
    "last_name": "Poschel",
    "name": "Greg Poschel",
    "phone": "734-951-1518",
    "property_type": "Apartment",
    "location": "Abelheira",
    "number_duration": 9,
    "period": "month",
    "start_date": "24/1/2022",
    "end_date": "25/4/2022",
    "duration": "9 / month",
    "status": "Past"
}, {
    "id": 16,
    "first_name": "Vinny",
    "last_name": "Bricket",
    "name": "Vinny Bricket",
    "phone": "155-130-3664",
    "property_type": "Apartment",
    "location": "Piedras",
    "number_duration": 5,
    "period": "year",
    "start_date": "20/1/2022",
    "end_date": "15/3/2022",
    "duration": "5 / year",
    "status": "Upcoming"
}, {
    "id": 17,
    "first_name": "Boot",
    "last_name": "Phear",
    "name": "Boot Phear",
    "phone": "138-615-8060",
    "property_type": "Single Room",
    "location": "Ipoh",
    "number_duration": 6,
    "period": "week",
    "start_date": "12/5/2022",
    "end_date": "28/12/2021",
    "duration": "6 / week",
    "status": "Upcoming"
}, {
    "id": 18,
    "first_name": "Nilson",
    "last_name": "Jotham",
    "name": "Nilson Jotham",
    "phone": "864-831-3202",
    "property_type": "Single Room",
    "location": "Chaviña",
    "number_duration": 3,
    "period": "month",
    "start_date": "14/2/2022",
    "end_date": "7/6/2022",
    "duration": "3 / month",
    "status": "Past"
}, {
    "id": 19,
    "first_name": "Ingeberg",
    "last_name": "Goode",
    "name": "Ingeberg Goode",
    "phone": "704-786-6391",
    "property_type": "Single Room",
    "location": "Nentón",
    "number_duration": 2,
    "period": "year",
    "start_date": "1/5/2022",
    "end_date": "5/7/2022",
    "duration": "2 / year",
    "status": "Current"
}, {
    "id": 20,
    "first_name": "Humphrey",
    "last_name": "Bresson",
    "name": "Humphrey Bresson",
    "phone": "924-559-4489",
    "property_type": "Single Room",
    "location": "Bafoussam",
    "number_duration": 1,
    "period": "month",
    "start_date": "10/12/2021",
    "end_date": "15/4/2022",
    "duration": "1 / month",
    "status": "Current"
    }]

export const testListingData = [{
    "id": 1,
    "property_type": "Single room",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 3,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "200/month"
}, {
    "id": 2,
    "property_type": "Single room",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 2,
    "location": "Fosu",
    "region": "Accra",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "500/month"
}, {
    "id": 3,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "120/month"
}, {
    "id": 4,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 3,
    "location": "Fosu",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "500/month"
}, {
    "id": 5,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "350/month"
}, {
    "id": 6,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Accra",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 7,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Central",
    "favorite": 1,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "200/month"
}, {
    "id": 8,
    "property_type": "Apartment",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 2,
    "location": "Fosu",
    "region": "Central",
    "favorite": 1,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "120/month"
}, {
    "id": 9,
    "property_type": "Single room",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 3,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 10,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 11,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 2,
    "location": "Fosu",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 12,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 13,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 4,
    "location": "Kumasi",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "500/month"
}, {
    "id": 14,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "1000/month"
}, {
    "id": 15,
    "property_type": "Single room",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "500/month"
}, {
    "id": 16,
    "property_type": "Single room",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 3,
    "location": "Kumasi",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 17,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Accra",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "120/month"
}, {
    "id": 18,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 2,
    "location": "Accra",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 19,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "1000/month"
}, {
    "id": 20,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 1,
    "location": "Fosu",
    "region": "Central",
    "favorite": 1,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "1000/month"
}, {
    "id": 21,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 1,
    "location": "Accra",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "1000/month"
}, {
    "id": 22,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 1,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "1000/month"
}, {
    "id": 23,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 2,
    "location": "Accra",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "500/month"
}, {
    "id": 24,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 4,
    "location": "Accra",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 25,
    "property_type": "Single room",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 26,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 3,
    "location": "Fosu",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "1000/month"
}, {
    "id": 27,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "500/month"
}, {
    "id": 28,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 4,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "350/month"
}, {
    "id": 29,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Central",
    "favorite": 1,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "1000/month"
}, {
    "id": 30,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 31,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "120/month"
}, {
    "id": 32,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "1000/month"
}, {
    "id": 33,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 1,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "350/month"
}, {
    "id": 34,
    "property_type": "Single room",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 2,
    "location": "Fosu",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "1000/month"
}, {
    "id": 35,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 1,
    "location": "Fosu",
    "region": "Accra",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "500/month"
}, {
    "id": 36,
    "property_type": "Single room",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 1,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "200/month"
}, {
    "id": 37,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 1,
    "location": "Kumasi",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 38,
    "property_type": "Single room",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 4,
    "location": "Accra",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 39,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 1,
    "location": "Accra",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 40,
    "property_type": "Apartment",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 2,
    "location": "Accra",
    "region": "Accra",
    "favorite": 1,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "500/month"
}, {
    "id": 41,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "350/month"
}, {
    "id": 42,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "350/month"
}, {
    "id": 43,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 1,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "200/month"
}, {
    "id": 44,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 4,
    "location": "Accra",
    "region": "Central",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 45,
    "property_type": "Single room",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 3,
    "location": "Accra",
    "region": "Kumasi",
    "favorite": 0,
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiaX68oWNSI-8GcQrqlFDpCx7Th6phXMCQWg&usqp=CAU",
    "amount": "350/month"
}, {
    "id": 46,
    "property_type": "Apartment",
    "number_of_bathrooms": 2,
    "number_of_bedrooms": 2,
    "location": "Fosu",
    "region": "Kumasi",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "350/month"
}, {
    "id": 47,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 3,
    "location": "Kumasi",
    "region": "Central",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "500/month"
}, {
    "id": 48,
    "property_type": "Apartment",
    "number_of_bathrooms": 4,
    "number_of_bedrooms": 2,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 0,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "500/month"
}, {
    "id": 49,
    "property_type": "Apartment",
    "number_of_bathrooms": 3,
    "number_of_bedrooms": 4,
    "location": "Kumasi",
    "region": "Accra",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/empty-road-at-building-exterior-picture-id479842074?k=20&m=479842074&s=612x612&w=0&h=HS6lsU1f9W21IkotS3cxdvU5KeEO-gLMUa6xrIBbR6k=",
    "amount": "200/month"
}, {
    "id": 50,
    "property_type": "Single room",
    "number_of_bathrooms": 1,
    "number_of_bedrooms": 4,
    "location": "Fosu",
    "region": "Accra",
    "favorite": 1,
    "image": "https://media.istockphoto.com/photos/low-angle-of-tall-building-in-manhattan-picture-id1291177121?b=1&k=20&m=1291177121&s=170667a&w=0&h=aI1PkWS_GkXJ4Qz0gz2cTOud95SS4hUa4iZc1kqWYL4=",
    "amount": "1000/month"
}]